version: '3.8'
networks:
  internal:
    name: internal
    external: false 
  default:
    name: gateway 
services:
  app:
    image: rustlang/rust:nightly
    build:
      context: services/dao
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8000:8000/tcp
    networks:
      - internal
  reverse_proxy:
    image: nginx
    container_name: reverse_proxy
    ports:
      - 80:80/tcp
    networks:
      - default
  node:
    image: solanalabs/solana:beta
    ports:
      - 8001/tcp
      - 8899-8902/tcp
      - 8000-8009/udp
      - 9900/tcp
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
  indexer:
    image: elasticsearch
    build:
      context: services/elasticsearch
      dockerfile: Dockerfile 
    container_name: indexer
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - internal
  grapher:
    image: kibana
    build:
      context: services/kibana
      dockerfile: Dockerfile 
    container_name: grapher
    ports:
      - 5601:5601
    networks:
      - internal
  logger:
    image: logstash
    build:
      context: services/logstash
      dockerfile: Dockerfile 
    container_name: logstash
    ports:
      - 5044:5044
    networks:
      - internal