cluster.name: "elastic_node"

network.host: 0.0.0.0
transport.host: 0.0.0.0

enforce.bootstrap.checks: true

bootstrap.memory_lock: true

discovery.zen.minimum_master_nodes: 1
discovery.type: single-node
discovery.zen.ping.unicast.hosts: "0.0.0.0:9200"

#-XX:PermSize=256m -XX:MaxPermSize=1024m -XX:ReservedCodeCacheSize=64m -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled -XX:+PrintHeapAtGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"

#xpack.license.self_generated.type: trial
#xpack.security.enabled: true
#xpack.security.http.ssl.enabled: true
#xpack.security.http.ssl.verification_mode: certificate
#xpack.security.http.ssl.key:  certs/elasticsearch/elasticsearch.key
#xpack.security.http.ssl.certificate: certs/elasticsearch/elasticsearch.crt
#xpack.security.http.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]
#xpack.security.transport.ssl.enabled: true
#xpack.security.transport.ssl.key:  certs/elasticsearch/elasticsearch.key
#xpack.security.transport.ssl.certificate: certs/elasticsearch/elasticsearch.crt
#xpack.security.transport.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]