[programs.localnet]
dao_app = "f66Y7yepbcCmqXW5KxWXkJa2mPk4qsbWg5Sc7ELVmEM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/devx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
